- platform: template
  switches:
    camera_garagewx_ir_lights:
      value_template: "{{ is_state_attr('camera.garagewx', 'ir_lights_enabled', true) }}"
      turn_on:
        service: camera.enable_ir_lights
        data:
          entity_id: camera.garagewx
      turn_off:
        service: camera.disable_ir_lights
        data:
          entity_id: camera.garagewx
      icon_template: >-
        {% if is_state_attr('camera.garagewx', 'ir_lights_enabled', true) %}
          mdi:flashlight
        {% else %}
          mdi:flashlight-off
        {% endif %}

    camera_garagewx_motion_detection:
      value_template: "{{ is_state_attr('camera.garagewx', 'motion_detection_enabled', true) }}"
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.garagewx
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.garagewx
      icon_template: >-
        {% if is_state_attr('camera.garagewx', 'motion_detection_enabled', true) %}
          mdi:motion-sensor
        {% else %}
          mdi:motion-sensor-off
        {% endif %}

        