#
# Group notification
#
# All notifications are sent to groups to mimimize hard-coding notification
# services throughout the code base.
#
# @link https://home-assistant.io/components/notify.group/
#
- platform: group
  name: Sound
  services:
    - service: join

- platform: group
  name: Speech
  services:
    - service: fully_kiosk
    # - service: join

- platform: group
  name: Text
  services:
    - service: join


- platform: group
  name: Mobile
  services:
    - service: mobile_app_galaxy_s10
    - service: mobile_app_galaxys10
    - service: mobile_app_kfauwi
    - service: mobile_app_seans_iphone
    - service: mobile_app_wedge
    - service: mobile_app_shield_android_tv
