- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: 192.168.100.3
  #port: 80
  days: 7
  ssl: false
  max: 10
- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: 192.168.100.3
  #port: 80
  days: 120
  ssl: false
  theaters: true
  max: 10