esphomeyaml:
  name: wx_esp32_01
  platform: ESP32
  board: wemosbat

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mq_broker
  username: !secret mq_username
  password: !secret mq_password

# Enable logging
logger:

ota:
