  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=780429868&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=780429868&user=icu&pwd=
    name: Office
  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=1416143838&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=1416143838&user=icu&pwd=
    name: Living Room
  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=921650163&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=921650163&user=icu&pwd=
    name: Garage
  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=761237969&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=761237969&user=icu&pwd=
    name: Backyard
  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=784827467&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=784827467&user=icu&pwd=
    name: Basement
  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=1005860495&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=1005860495&user=icu&pwd=
    name: Oakbluff Front
  - platform: mjpeg
    mjpeg_url: http://192.168.100.128:8083/axis-cgi/mjpg/video.cgi?cameraId=2133160954&user=icu&pwd=
    still_image_url: http://192.168.100.128:8083/axis-cgi/jpg/image.cgi?cameraId=2133160954&user=icu&pwd=
    name: Oakbluff Patio